[build]
  command = "chmod +x netlify-build.sh && ./netlify-build.sh"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18.18.0"
  NPM_VERSION = "9.8.0"
  CI = "false"
  NPM_FLAGS = "--legacy-peer-deps"
  NETLIFY_USE_PNPM = "false"
  NETLIFY_NEXT_PLUGIN_SKIP = "false"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# 配置错误页面回退
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
  conditions = {error = true}

# 添加缓存控制
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable" 